<?php echo $this->partial('flashmessenger.phtml'); ?>
<h1><?php echo ($this->grupo)? 'Editar ' : 'Adicionar novo '?>Grupo</h1>

<form class="form-horizontal" method="post">
    <?php if($this->grupo): ?>
        <input type="hidden" name="id_grupo" value="<?php echo $this->grupo->id_grupo; ?>">
    <?php endif; ?>
    <div class="control-group">
        <label class="control-label" for="nome">Nome</label>
        <div class="controls">
            <input id="nome" name="nome" value="<?php echo ($this->grupo) ? $this->grupo->nome : ''; ?>" class="input-xlarge" placeholder="Nome do Grupo"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="descricao">Descrição</label>
        <div class="controls">
            <input id="descricao" name="descricao" value="<?php echo ($this->grupo) ? $this->grupo->descricao : ''; ?>" class="input-xlarge" placeholder="Descrição do Grupo"/>
        </div>
    </div>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">Gravar</button>
        <button class="btn btn-danger" type="reset">Limpar</button>
        <button class="btn" type="button" onclick="window.history.back();">Voltar</button>
    </div>
</form>