<?php echo $this->partial('flashmessenger.phtml'); ?>
<h1>Listagem de Grupos</h1>

<?php if (count($this->grupos)): ?>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th width="200px">Ações</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->grupos as $grupo) : ?>
            <tr>
                <td><?php echo $grupo->id_grupo; ?></td>
                <td><?php echo $grupo->nome; ?></td>
                <td><?php echo $grupo->descricao; ?></td>
                <td>
                    <button class="btn btn-primary"
                            onclick="window.location.href='/agenda/grupo/editar/<?php echo $grupo->id_grupo; ?>';">
                        Editar
                    </button>
                    <button class="btn btn-danger"
                            onclick="if(confirm('Deseja remover este grupo?')) { window.location.href='/agenda/grupo/remover/<?php echo $grupo->id_grupo; ?>'}">
                        Remover
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3">&nbsp;</td>
        </tr>
        </tfoot>
    </table>
<?php else: ?>
    <p>Nenhum grupo para listar</p>
<?php endif; ?>
